export const MainPage = () => ((
  <div className="main-page">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum pulvinar etiam non quam lacus suspendisse. Justo eget magna fermentum iaculis eu non diam. Purus in mollis nunc sed id semper risus in. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Enim tortor at auctor urna nunc. Condimentum lacinia quis vel eros donec ac odio. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Ornare massa eget egestas purus viverra accumsan in nisl nisi.

Mi tempus imperdiet nulla malesuada pellentesque elit. Ac tortor vitae purus faucibus ornare suspendisse. Hac habitasse platea dictumst quisque. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Cum sociis natoque penatibus et. Ultricies mi quis hendrerit dolor magna eget est. Netus et malesuada fames ac turpis egestas integer eget aliquet. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Ornare quam viverra orci sagittis eu volutpat odio facilisis. Amet consectetur adipiscing elit pellentesque habitant morbi. Tincidunt augue interdum velit euismod in pellentesque massa. Nunc scelerisque viverra mauris in aliquam sem. Feugiat in ante metus dictum at. Turpis egestas sed tempus urna. Fames ac turpis egestas integer eget aliquet nibh praesent. Eget nullam non nisi est sit amet facilisis magna etiam. In cursus turpis massa tincidunt dui ut ornare lectus sit. Et pharetra pharetra massa massa. Fermentum et sollicitudin ac orci phasellus egestas tellus.

Elementum integer enim neque volutpat. At tempor commodo ullamcorper a lacus vestibulum. Id nibh tortor id aliquet lectus proin. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. In tellus integer feugiat scelerisque varius morbi enim. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Turpis egestas maecenas pharetra convallis. Porttitor rhoncus dolor purus non enim praesent. Ac auctor augue mauris augue neque. Etiam erat velit scelerisque in dictum non consectetur. Sollicitudin tempor id eu nisl nunc. Viverra justo nec ultrices dui sapien eget mi proin sed. Commodo sed egestas egestas fringilla phasellus faucibus. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Tincidunt ornare massa eget egestas purus viverra accumsan. Aliquam eleifend mi in nulla posuere. Amet risus nullam eget felis eget nunc lobortis. Sem nulla pharetra diam sit amet nisl suscipit.

Ornare suspendisse sed nisi lacus sed viverra. Arcu bibendum at varius vel pharetra. Interdum velit laoreet id donec ultrices tincidunt. Fringilla est ullamcorper eget nulla. Congue eu consequat ac felis donec et odio. Id neque aliquam vestibulum morbi blandit cursus. Maecenas volutpat blandit aliquam etiam erat velit. Tempor orci dapibus ultrices in iaculis. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Ornare quam viverra orci sagittis eu volutpat odio. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Dolor magna eget est lorem. Tristique sollicitudin nibh sit amet commodo.

Vel quam elementum pulvinar etiam. Aliquam ut porttitor leo a diam sollicitudin tempor. Sed faucibus turpis in eu mi bibendum neque egestas congue. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Nec nam aliquam sem et tortor consequat id. Vulputate dignissim suspendisse in est ante in nibh mauris. Libero id faucibus nisl tincidunt eget nullam. Cras sed felis eget velit aliquet sagittis. A erat nam at lectus urna. Aliquet sagittis id consectetur purus. Adipiscing elit ut aliquam purus sit amet. Scelerisque in dictum non consectetur a erat nam at. Donec adipiscing tristique risus nec feugiat in fermentum. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Sit amet commodo nulla facilisi nullam. Faucibus nisl tincidunt eget nullam non. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Tortor at auctor urna nunc id cursus metus aliquam. Et netus et malesuada fames ac turpis. Nam libero justo laoreet sit amet cursus sit amet dictum.

Viverra justo nec ultrices dui. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Euismod nisi porta lorem mollis aliquam ut. Massa enim nec dui nunc mattis enim. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Diam maecenas ultricies mi eget mauris pharetra et. Nibh nisl condimentum id venenatis. Nisl rhoncus mattis rhoncus urna neque. Ipsum dolor sit amet consectetur. Sit amet nulla facilisi morbi. Enim eu turpis egestas pretium aenean pharetra magna. Eu non diam phasellus vestibulum lorem. Turpis egestas integer eget aliquet. Nunc consequat interdum varius sit amet mattis.

Nibh praesent tristique magna sit. Nibh cras pulvinar mattis nunc. Eu tincidunt tortor aliquam nulla facilisi cras. Diam phasellus vestibulum lorem sed risus. Ipsum faucibus vitae aliquet nec ullamcorper sit. Maecenas sed enim ut sem viverra aliquet eget sit amet. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Faucibus scelerisque eleifend donec pretium vulputate. Laoreet sit amet cursus sit amet. Augue eget arcu dictum varius duis at consectetur lorem. Consectetur libero id faucibus nisl tincidunt eget nullam. Varius quam quisque id diam. Curabitur vitae nunc sed velit dignissim sodales ut. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Risus pretium quam vulputate dignissim suspendisse. Egestas quis ipsum suspendisse ultrices gravida. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Sed faucibus turpis in eu mi bibendum neque egestas.
  </div>
));